apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: run-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: run-deploy
        image: tobegit3hub/cloud-tensorflow-run-deploy
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
